"""
    Module to start-up the grid and create
    all according and needed car objects with
    their drivers.

    Drivers will be generated by default names without
    using real names.
"""

#=====Imports=========================================

#=====Module Imports==================================
from src.config import (
    NUMBER_OF_COMPETITORS,
    RACE_START_OFFSET
)
from src.const import (
    DEFAULT_DRIVER_NAME, 
    DEFAULT_DRIVER_SHORT, 
    GRID_CACHE,
    HARD,
    MEDIUM,
    SOFT
)

from src.cars import Car
from src.drivers import Driver
from src.tyre import Tyre

#=====Libraries=======================================


#=====Functions=======================================
def build_grid():
    """
    Generate all necessary drivers and cars
    Save according information to the grid#

    TODO
        - How to set different skill levels? Now default
        - How to set different car power levels, but same for two cars
        - How to give different cars different tyres
    """

    # To seperate the field in the beginning
    starting_offset = 0

    # Reset the Grid
    GRID_CACHE.clear()

    # Generate a starting grid
    for i in range(NUMBER_OF_COMPETITORS):

        # Make sure there are only three letters
        # per driver short
        if i < 9:
            driver_number = "0" + f"{i+1}"
        else:
            driver_number = f"{i+1}"

        driver = Driver(
            name=DEFAULT_DRIVER_NAME + driver_number,
            short=DEFAULT_DRIVER_SHORT + driver_number,
            skill=0.5
        )

        tyre = Tyre(compound=SOFT)

        car = Car(
            driver=driver,
            power=0.5,
            tyre=tyre,
            position=i+1,
            race_time=starting_offset
        )

        starting_offset += RACE_START_OFFSET

        GRID_CACHE.append(car)
